#!/bin/bash
echo ================ Creating directories... ================

files=(output/company/ output/panel/)
for file in ${files[@]}
do
    echo mkdir -p $file
    mkdir -p $file
done
printf "================ Finished creating directories ================\n\n"

pyfiles=(featurize/featurize.py)
for file in ${pyfiles[@]}
do
    echo ================ Running python3 $file ================
    python3 $file
    if [ $? -eq 1 ]; then
        echo Failed. Make sure you import all the correct libraries
        break
    fi
    echo ================ Finished python3 $file ================
    printf "\n\n"
done